### ISSUE TITLE
Release checklist 0.8

### ISSUE THREAD

**Issue by tmpfs** [saveoursecrets/sdk#258]
* [x] Merge #219
* [x] Complete #255 
* [x] Publish crates as 0.8 (sos-sdk, sos-net, sos)
* [x] Tag a new 0.8 version to update github releases, homebrew etc.
* [x] Update website with new CLI release
